"""The Pine port of crucible.edge cannot drift from crucible silently.

`pine/CrucibleEdge.pine` is a function-for-function port of `crucible.edge`, checked on a
chart by `pine/CrucibleEdgeConformance.pine`, whose expected values were produced by
crucible itself (`pine/gen_vectors.py`). These tests close the loop from this side:

1. the committed `pine/vectors.json` equals what the current crucible produces, so any
   change to an edge metric fails here until the vectors are regenerated;
2. every expected value embedded in the conformance script matches those vectors, so a
   regenerated vectors.json cannot be committed without the Pine script following.

Nothing here runs Pine; TradingView compiles it, and the conformance table on a chart is
the other half of the check.
"""
from __future__ import annotations

import importlib.util
import json
import math
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PINE = ROOT / "pine"


def _load_gen():
    spec = importlib.util.spec_from_file_location("gen_vectors", PINE / "gen_vectors.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


gen = _load_gen()

# The ten trailing arguments of each `mk("name", ...)` call in the conformance script, in
# the order gen.METRICS lists them. Numbers are unquoted; metrics that can be inf or nan are
# quoted strings.
_TAIL = (r'mk\("(?P<name>\w+)",(?:.*?)'
         r'(?P<n>\d+), (?P<wr>[-\d.]+), (?P<e>[-\d.]+), "(?P<pf>[^"]+)", "(?P<po>[^"]+)", '
         r'(?P<sq>[-\d.]+), "(?P<ex>[^"]+)", "(?P<ta>[^"]+)", "(?P<ee>[^"]+)", (?P<dd>[-\d.]+)\)\)')


def _embedded_expectations() -> dict[str, dict[str, str]]:
    src = (PINE / "CrucibleEdgeConformance.pine").read_text()
    found = {}
    for m in re.finditer(_TAIL, src, re.S):
        vals = (m["n"], m["wr"], m["e"], m["pf"], m["po"], m["sq"], m["ex"], m["ta"], m["ee"], m["dd"])
        found[m["name"]] = dict(zip(gen.METRICS, vals))
    return found


def _close(got: str, want, tol: float = 1e-6) -> bool:
    if want is None:              # crucible leaves an optional metric None; Pine reads na, the script says "nan"
        return got == "nan"
    if want in ("inf", "nan"):
        return got == want
    if isinstance(want, int) and not isinstance(want, bool):
        return int(got) == want
    return math.isclose(float(got), float(want), abs_tol=tol)


def test_committed_vectors_match_the_current_crucible():
    committed = json.loads((PINE / "vectors.json").read_text())
    current = gen.vectors()
    assert committed["cases"].keys() == current["cases"].keys()
    for name, case in current["cases"].items():
        for metric, want in case["expected"].items():
            got = committed["cases"][name]["expected"].get(metric)
            if isinstance(want, float) and got is not None and not isinstance(got, str):
                assert math.isclose(got, want, abs_tol=1e-9), (
                    f"{name}.{metric}: vectors.json has {got}, crucible now gives {want}. "
                    "An edge metric changed; run `python pine/gen_vectors.py --write` and update "
                    "pine/CrucibleEdgeConformance.pine to match, then republish the Pine library.")
            else:
                assert got == want, f"{name}.{metric}: vectors.json has {got!r}, crucible now gives {want!r}"


def test_conformance_script_embeds_the_vectors():
    embedded = _embedded_expectations()
    current = gen.vectors()["cases"]
    assert embedded.keys() == current.keys(), (
        f"conformance script cases {sorted(embedded)} != vectors {sorted(current)}")
    for name, case in current.items():
        for metric in gen.METRICS:
            want = case["expected"][metric]
            got = embedded[name][metric]
            assert _close(got, want), (
                f"{name}.{metric}: CrucibleEdgeConformance.pine embeds {got}, crucible gives {want}")


@pytest.mark.parametrize("name", list(gen.CASES))
def test_case_inputs_are_what_the_script_builds(name):
    """The r arrays in the script must be the arrays the vectors were computed from."""
    src = (PINE / "CrucibleEdgeConformance.pine").read_text()
    if name == "n150":
        assert "((i * 7919) % 13 - 5) / 4.0" in src
        return
    r = gen.CASES[name]["r"]
    literal = "array.from(" + ", ".join(_pine_num(x) for x in r) + ")"
    assert literal in src, f"{name}: r array {literal} not found in the conformance script"


def _pine_num(x: float) -> str:
    s = repr(float(x))
    return s


def test_vectors_carry_the_crucible_version_they_were_made_with():
    import crucible
    committed = json.loads((PINE / "vectors.json").read_text())
    assert committed["crucible_version"] == crucible.__version__, (
        "vectors.json was generated by a different crucible; regenerate with "
        "`python pine/gen_vectors.py --write` so the recorded version is honest")
